import os
import shutil

print(os.getcwd())
print(os.listdir())
print(os.listdir('C:\\'))
os.chdir('C:\\Users\\arka.roy\\Documents\\Python Scripts\\Django Full Stack\\python\\Exercises\\DS_Algorithms')
print(os.getcwd())
print(os.listdir())
f=open("old.txt",'w',encoding = 'utf-8')
f.write("Hello!")
f.close()
print(os.listdir())
f=open("old.txt",'r',encoding = 'utf-8')
print(f.read())
f.close()
os.mkdir('test')
print(os.listdir())
os.rename('test','new_one')
print(os.listdir())
os.remove('old.txt')
print(os.listdir())
os.rmdir('new_one')
print(os.listdir())
os.mkdir('test')
print(os.listdir())
os.chdir('test')
print(os.getcwd())
print(os.listdir())
f=open("test.txt",'w',encoding = 'utf-8')
f.write("Hello!")
f.close()
print(os.listdir())
f=open("test.txt",'r',encoding = 'utf-8')
print(f.read())
f.close()
os.chdir('C:\\Users\\arka.roy\\Documents\\Python Scripts\\Django Full Stack\\python\\Exercises\\DS_Algorithms')
print(os.getcwd())
# os.rmdir('test') won't work because directory is not empty
shutil.rmtree('test')
print(os.listdir())
